apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
spec:
  type: ClusterIP
  selector:
    app: home
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: ClientIP