apiVersion: v1
kind: Service
metadata:
  name: isomorphic
  labels:
    app: isomorphic
spec:
  type: ClusterIP
  selector:
    app: isomorphic
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: ClientIP