apiVersion: v1
kind: Service
metadata:
  name: header
  labels:
    app: header
spec:
  type: ClusterIP
  selector:
    app: header
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: ClientIP