apiVersion: v1
kind: Service
metadata:
  name: angular-seed
  labels:
    app: angular-seed
spec:
  type: ClusterIP
  selector:
    app: angular-seed
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: ClientIP